#creating a prompt for the summary,Argument,cases and procedural formatting
#Dictionary to access the  prompt
summary_format_prompt = """
    # Summary of Research Findings
    **Generated by: [Pragati.ai-Research Engine]**
    **Date and Time: [Generation Date and Time] catch it reatime time and date generator**

    ## Case Reference: [Case Number/Identifier]

    ### I. Introduction
    A. Background of the Case
    B. Scope of Research

    ### II. Summary of Saved Chat Data
    A. Key Points from Decision Facilitator Engine
    B. Relevant User Interactions
    C. Model Consultancy Insights

    ### III. Analysis of Saved Summary Data
    A. Overview of summary Results
    B. LLM Summarizer Findings
    C. Synthesis of Information from Various Sources

    ### IV. Review of Previously Saved Document Data
    A. Relevant Legal Precedents
    B. Applicable Procedures and Arguments
    C. Potential Case Outcomes

    ### V. Conclusions and Recommendations
    A. Primary Findings
    B. Suggested Course of Action
    C. Potential Implications

    ### VI. Appendices
    A. List of Referenced Documents
    B. Glossary of Key Terms
    C. Additional Supporting Information

    ------------------------------------------------------------------------------

    *This document is a computer-generated summary based on the data collected and analyzed by [Research Engine Name]. While efforts have been made to ensure accuracy, this summary should not be considered as legal advice. Please consult with a qualified legal professional for interpretation and application of this information.*"""



argumentt_format_prompt = """
    # Legal Argument
    **Prepared by: [Pragati.ai-Research Engine]**
    **Date: [Current Date]**

    ## Case Information
    - Case Number: [Case Number]
    - Parties Involved: [Plaintiff] v. [Defendant]

    ### I. Introduction
    A. Statement of the Issue
    B. Brief Overview of the Argument

    ### II. Facts of the Case
    A. Relevant Background Information
    B. Key Events and Dates

    ### III. Legal Principles
    A. Applicable Laws and Statutes
    B. Relevant Case Precedents

    ### IV. Argument
    A. Main Contention
    B. Supporting Points
        1. First Point
        2. Second Point
        3. Third Point
    C. Addressing Counterarguments

    ### V. Evidence
    A. Documentary Evidence
    B. Witness Testimonies
    C. Expert Opinions

    ### VI. Relief Sought
    A. Specific Requests to the Court
    B. Justification for the Requested Relief

    ### VII. Conclusion
    A. Summary of Key Arguments
    B. Reiteration of Desired Outcome

    ------------------------------------------------------------------------------

    *This document is a computer-generated legal argument based on the data analyzed by [Research Engine Name]. It should not be considered as legal advice. Please consult with a qualified legal professional before using this information in any legal proceedings.*
"""

procedure_format_prompt = """
    # Legal Procedure Guide
    **Generated by: [Pragati.ai-Research Engine]**
    **Last Updated: [Current Date and Time]**

    ## Case Reference: [Case Number/Identifier]

    ### I. Pre-Trial Procedures
    A. Filing the Complaint
    B. Serving the Defendant
    C. Defendant's Response
    D. Discovery Process
        1. Interrogatories
        2. Depositions
        3. Document Requests
    E. Pre-Trial Motions

    ### II. Trial Preparation
    A. Jury Selection (if applicable)
    B. Opening Statements
    C. Witness Preparation
    D. Exhibit Organization

    ### III. Trial Procedure
    A. Presentation of Evidence
    B. Examination of Witnesses
        1. Direct Examination
        2. Cross-Examination
        3. Redirect and Recross
    C. Objections and Rulings
    D. Closing Arguments

    ### IV. Post-Trial Procedures
    A. Verdict or Judgment
    B. Post-Trial Motions
    C. Appeals Process (if necessary)

    ### V. Alternative Dispute Resolution
    A. Mediation
    B. Arbitration

    ### VI. Specific Jurisdictional Procedures
    A. Local Court Rules
    B. Case Management Conferences

    ### VII. Timelines and Deadlines
    A. Statute of Limitations
    B. Filing Deadlines
    C. Court-Imposed Deadlines

    ------------------------------------------------------------------------------

    *This document is a computer-generated guide to legal procedures based on the data analyzed by [Research Engine Name]. It should not be considered as legal advice. Please consult with a qualified legal professional for accurate and up-to-date procedural information specific to your jurisdiction.*
"""

decision_format_prompt = """
    # Legal Decision Analysis
    **Prepared by: [Pragati.ai-Research Engine]**
    **Analysis Date: [Current Date]**

    ## Case Information
    - Case Name: [Case Name]
    - Citation: [Official Citation]
    - Court: [Court Name]
    - Date of Decision: [Decision Date]

    ### I. Background
    A. Parties Involved
    B. Procedural History

    ### II. Facts of the Case
    A. Key Events
    B. Disputed Issues

    ### III. Legal Questions Presented
    A. Primary Legal Issues
    B. Secondary Considerations

    ### IV. Court's Analysis
    A. Majority Opinion
        1. Legal Reasoning
        2. Application of Law to Facts
        3. Policy Considerations
    B. Concurring Opinions (if any)
    C. Dissenting Opinions (if any)

    ### V. Holding and Ruling
    A. Final Decision
    B. Specific Orders or Remedies

    ### VI. Implications of the Decision
    A. Immediate Effects on Parties
    B. Broader Legal Impact
    C. Potential Future Applications

    ### VII. Critical Analysis
    A. Strengths of the Decision
    B. Potential Weaknesses or Criticisms
    C. Comparison with Related Cases

    ### VIII. Conclusion
    A. Summary of Key Points
    B. Significance in Legal Landscape

    ------------------------------------------------------------------------------

    *This document is a computer-generated analysis of a legal decision based on the data processed by [Research Engine Name]. It should not be considered as legal advice or an official interpretation of the court's ruling. Please consult with a qualified legal professional for authoritative interpretation and application of this decision.*
"""

case_analysis_format_prompt = """
    # Comprehensive Case Analysis
    **Produced by: [Pragati.ai-Research Engine]**
    **Analysis Date: [Current Date and Time]**

    ## Case Identification
    - Case Name: [Full Case Name]
    - Docket Number: [Court Docket Number]
    - Jurisdiction: [Court and Jurisdiction]

    ### I. Executive Summary
    A. Brief Overview of Case
    B. Key Issues and Outcomes

    ### II. Factual Background
    A. Chronology of Events
    B. Parties Involved
    C. Underlying Circumstances

    ### III. Procedural History
    A. Initial Filing
    B. Pre-Trial Proceedings
    C. Trial Court Proceedings
    D. Appellate History (if applicable)

    ### IV. Legal Issues
    A. Primary Questions of Law
    B. Subsidiary Legal Issues
    C. Relevant Statutes and Precedents

    ### V. Arguments Presented
    A. Plaintiff's/Appellant's Arguments
    B. Defendant's/Respondent's Arguments
    C. Amicus Curiae Contributions (if any)

    ### VI. Court's Analysis and Reasoning
    A. Majority Opinion
    B. Concurring Opinions
    C. Dissenting Opinions

    ### VII. Decision and Holding
    A. Final Ruling
    B. Specific Orders and Remedies
    C. Vote Distribution (for appellate decisions)

    ### VIII. Legal Principles Established or Affirmed
    A. New Legal Rules or Standards
    B. Clarifications of Existing Law
    C. Overturned Precedents (if any)

    ### IX. Impact and Implications
    A. Immediate Consequences for Parties
    B. Broader Legal Implications
    C. Social, Economic, or Political Ramifications

    ### X. Critical Evaluation
    A. Strengths of the Decision
    B. Potential Weaknesses or Criticisms
    C. Unresolved Questions

    ### XI. Comparative Analysis
    A. Relationship to Prior Cases
    B. Consistency with Legal Trends
    C. International Law Considerations (if applicable)

    ### XII. Future Outlook
    A. Potential for Further Appeals
    B. Likely Influence on Future Cases
    C. Possible Legislative Responses

    ### XIII. Conclusion
    A. Recap of Key Points
    B. Overall Significance in Legal Landscape

    ### XIV. Appendices
    A. Key Evidence Summary
    B. Timeline of Case Progression
    C. Glossary of Specialized Terms

    ------------------------------------------------------------------------------

    *This document is a computer-generated comprehensive analysis based on the data processed by [Research Engine Name]. While every effort has been made to ensure accuracy and thoroughness, this analysis should not be considered as legal advice. For authoritative interpretation and application of this case, please consult with a qualified legal professional.*
"""


# global formats_dict
formats_dict = {
    "format1": summary_format_prompt,
    "format2": argumentt_format_prompt,
    "format3": procedure_format_prompt,
    "format4": decision_format_prompt,
    "format5": case_analysis_format_prompt
}
